dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=cargo-cmd
    - RUST_BACKTRACE=1

matrix:
  include:
    - env: TARGET=armv7-unknown-linux-gnueabihf
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-musl
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      rust: nightly
      os: osx
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
      rust: nightly

before_install:
  - set -e

install:
  - sh scripts/install.sh
  - source ~/.cargo/env || true

script:
  - bash scripts/script.sh

after_script: set +e

before_deploy:
  - sh scripts/before_deploy.sh

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  api_key:
    secure: "D2x2OL0UwvDr0aG0MYLfW+EgMI/tIEeoSJCAHAG1IOpWMU5UUlNKd8LbNvAxDTlvnwbMU+L2X53A3RA/YJTyyklv9KzaUmg7upQxB3bsUXVJ1SFFBCmurcs+J5ScB0qCA1dnP/DEbtVDgsJiLgIfONoWBkUZKNR+cERUZQxe7XOMvZl8CCE9OqETlndS95aMC/MXvryOb38PHZfJa7WyAPB22Fe2BjNw+H9OLGHycOaPF82gkPxMO/ElI0AoCj6YVxeyAL1eN1p4tPTeXArluoHXDSID+70YmHTSuPm9Gkm8gCRTQTCLgjqzcYtQySFmuNNc4GJr4nsID1F6L0kYjrll+8i0GCQrdv/yN1RfF0Z1x/j7vNdZAik5arWFJlTypocEAHS+LLcRLSzMNMKEHWRRI2lSkJ6mkGV2zv5C4ZU6BO6AjhMCjy/1GmBG2CK7ygQAsUqEqoTa4r64GOl+J2a1on8lMcVB2AM+7S/c3UzOkzWsc8lgV4bGh3Myvf+vRTQmk2qDtAEGEjU1mdUcYHtd0MJSSC7OkFnFMbV5UHcUoyse1ExpkB6U1BTksNVWiXIvMCPN+oiyt9G6aMvOefrdUJEgSaV/JuiIB7+931g7UWWuaCMWDHdR9AYx971Oba55K+s5kTusXSf5uP+pAErHoNTdXPr88MHwNtCayt4="
  on:
    tags: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
    on_failure: never
