[package]
name = "cargo-cmd"
version = "0.1.0"
authors = ["Dan Reeves <hey@danreev.es>"]

[dependencies]
toml = "0.4.6"
serde_derive = "1.0.78"
serde = "1.0.78"
subprocess = "0.1.13"

[package.metadata.commands]
echo = "echo Hello planet!"
dev = "cargo watch -s 'clear; cargo build && cargo cmd echo'"
